### ISSUE TITLE
Regenerate yarp-matlab-bindings for yarp master branch

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp-matlab-bindings#44]
It is necessary after https://github.com/robotology/yarp/pull/2195 . Furthermore, we should switch to have v3.3 and master branches to mimic YARP branches.

**Comment by traversaro** [comment]
cc @gabrielenava that is the one that typically catches this regressions

**Comment by gabrielenava** [comment]
that's curious, I have wiped out and reinstalled the superbuild on Monday and I was able to compile without errors :-)

**Comment by traversaro** [comment]
Are you using the unstable branches?

**Comment by traversaro** [comment]
Fix for this provided in https://github.com/robotology/yarp-matlab-bindings/pull/46 .
