### ISSUE TITLE
ERROR using yarpMEX - Yarp MatLab bindings on MATLAB R2020b when mexErrMsgIdAndTxt  is invoked

### ISSUE THREAD

**Issue by giovannipizzolante** [robotology/yarp-matlab-bindings#62]
Hi @traversaro , when I try to go on for checking the  bindings installation, as suggested [here](https://github.com/robotology/robotology-superbuild/blob/master/doc/cmake-options.md#check-the-installation-6), when I type ``` yarpVec.fromMatlab([1;2;3]) ``` the following error is returned:
``` 
Error using yarpMEX
The error message identifier is invalid.

Error in yarp.Vector/fromMatlab (line 163)
      [varargout{1:nargout}] = yarpMEX(2590, self,
      varargin{:});

Error in SwigRef/subsref (line 33)
        [varargout{1:nargout}] =
        builtin('subsref',self,s);

```
Do you know how to solve this?

**Comment by traversaro** [comment]
I do not know in particular how to approach this problem, it could be due to some change in recent MATLAB R2020b that is not properly supported in SWIG. Anyhow, it seems to be similar to https://github.com/robotology/robotology-superbuild/issues/515 . Perhaps @lnobile could let us know how he worked around this, for example I guess you can set the elements of a YARP vector also with the setVal method?

**Comment by lnobile** [comment]
Hi everybody,
I ended up using bottles to write data on a port, an example:
```
 % writing to port example:

         port_points_opti = Port;                                        % create port
         port_points_opti.open('points_opti:o');                  % open port with desired name

          b_points_opti = Bottle();                                       % create bottle
          b_points_opti.clear();
          for kk = 1:size(opti_points_matrix,1)
              b_points_opti.addDouble(opti_points_mat(kk,1));  % add elements to bottle
          end
          port_points_opti.write(b_points_opti)                   % write to port
```

**Comment by traversaro** [comment]
Fixes for this issue are provided in:
* https://github.com/robotology/yarp-matlab-bindings/issues/62
* https://github.com/robotology/robotology-superbuild/pull/720

**Comment by traversaro** [comment]
https://github.com/robotology/yarp/pull/2564 was merged, now we just need to re-generate the bindings.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/yarp-matlab-bindings/pull/67 and released as https://github.com/robotology/yarp-matlab-bindings/releases/tag/v3.4.4 .
