### ISSUE TITLE
CMake configuration fails due to YCM

### ISSUE THREAD

**Issue by charlesdutau** [robotology/yarp-matlab-bindings#95]
As talked about in https://github.com/robotology/robotology-superbuild/issues/1418, I am trying to update yarp-matlab-bindings to 3.8 in order to bring it in sync with YARP. At this point, I have two YCM directories, one that was made separately and another as part of the robotology-superbuild sources. Regardless of which one I use, I get a CMake error when trying to configure yarp-matlab-bindings:

```
CMake Error at
 /home/cdutau/ycm/build/share/YCM/modules/InstallBasicPackageFiles.cmake:660
 (export):
   export Export set "yarp-matlab-bindings" not found.
 Call Stack (most recent call first):
   matlab/CMakeLists.txt:177 (install_basic_package_files)
```

Do I need to modify my YCM in some way in order to generate the bindings?

**Comment by traversaro** [comment]
Hi @charlesdutau, sorry I just saw the issue now (I have a bit of backlog due to ICRA). Were you able to solve your problem?

**Comment by charlesdutau** [comment]
Yes, ever since @corsinone rebuilt the robotology software, it is no longer an issue. Thank you!

**Comment by corsinone** [comment]
@traversaro thanks again! Hope to see you again soon! I am closing this issue :)
